name: Publish Npm Package

on:
  push:
    branches:
      - master

jobs:
  push-to-registry:
    name: Push to Npm registry
    runs-on: self-hosted
    steps:
      - name: Checkout Master branch
        uses: actions/checkout@v4
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_auth=${NPM_USERNAME}:${NPM_PASSWORD}" > ~/.npmrc
          npm publish --access public
        env:
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
