name: Publish Npm Package

on:
  push:
    branches:
      - master

jobs:
  push-to-registry:
    name: Push to Npm registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master branch
        uses: actions/checkout@v2

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
